// Static Question Bank for Avaliador CD
const staticLogicEasy = [
    { question: "Em lógica de programação, qual o resultado de: 10 + 5 * 2?", options: ["30", "20", "25", "15"], answer: 1 },
    { question: "O que é um valor 'Boolean'?", options: ["Um número decimal", "Um texto longo", "Um valor Verdadeiro ou Falso", "Uma lista de itens"], answer: 2 },
    { question: "Qual a função de um 'Loop' no código?", options: ["Encerrar o programa", "Limpar a memória", "Repetir um bloco de código", "Somar dois números"], answer: 2 },
    { question: "Qual é o primeiro índice de uma Lista em Python?", options: ["1", "0", "-1", "Inicia em qualquer número"], answer: 1 },
    { question: "Qual símbolo é geralmente usado para 'Igual a' em comparações?", options: ["=", "==", "=>", "!="], answer: 1 },
    { question: "Na lógica booleana, qual o resultado de '!true' (não verdadeiro)?", options: ["true", "null", "undefined", "false"], answer: 3 },
    { question: "O que o termo 'Software' representa?", options: ["As peças físicas do computador", "A parte lógica e os programas", "Apenas o monitor e teclado", "A conexão de internet"], answer: 1 },
    { question: "Qual o resultado da expressão lógica (5 > 3)?", options: ["Verdadeiro (True)", "Falso (False)", "Erro de sintaxe", "Nulo"], answer: 0 },
    { question: "Se x = 5 e executamos x = x + 1, qual o novo valor de x?", options: ["5", "4", "6", "10"], answer: 2 },
    { question: "Para que serve uma 'Variável' na programação?", options: ["Para exibir imagens", "Para armazenar dados na memória", "Para desligar o computador", "Para aumentar a velocidade do processador"], answer: 1 },
    { question: "Como se inicia um comentário de uma linha em Python?", options: ["#", "/*", "//", "--"], answer: 0 },
    { question: "Qual é o operador lógico para 'E' (AND)?", options: ["||", "&&", "!", "=="], answer: 1 },
    { question: "Qual é o operador lógico para 'OU' (OR)?", options: ["||", "&&", "!", "!="], answer: 0 },
    { question: "Em Python, qual caractere é usado para definir o início de um bloco de código (ex: após um 'if')?", options: [":", ".", ";", ","], answer: 0 },
    { question: "Qual palavra-chave é usada para declarar uma função em Python?", options: ["func", "def", "function", "define"], answer: 1 },
    { question: "Se 'Todos os desenvolvedores usam Git' e 'Ana é desenvolvedora', o que podemos afirmar?", options: ["Ana não usa Git", "Ana usa Git", "Ana usa SVN", "Ana não é desenvolvedora"], answer: 1 },
    { question: "Se 'Se chover, o deploy será cancelado'. Hoje choveu. O que aconteceu?", options: ["O deploy foi feito", "O deploy foi cancelado", "O servidor caiu", "Nada aconteceu"], answer: 1 },
    { question: "Interpretando: 'X é maior que Y' e 'Y é igual a Z'. Logo:", options: ["X é menor que Z", "X é maior que Z", "X é igual a Z", "Não há relação"], answer: 1 },
    { question: "Se 'A luz está acesa apenas se o interruptor estiver ligado'. A luz está apagada. Logo:", options: ["O interruptor está ligado", "O interruptor está desligado", "A lâmpada queimou", "Não podemos afirmar"], answer: 1 },
    { question: "Todo A é B. Algum C é A. Logo:", options: ["Todo C é B", "Algum C é B", "Nenhum C é B", "B é A"], answer: 1 },
    { question: "Se 'Se X é par, então X+1 é ímpar'. 10 é par. Logo:", options: ["11 é par", "11 é ímpar", "10 é ímpar", "Não podemos afirmar"], answer: 1 },
    { question: "O que é um 'Algoritmo'?", options: ["Um erro de sistema", "Uma sequência finita de passos para resolver um problema", "Uma peça de hardware", "Um tipo de monitor"], answer: 1 },
    { question: "Qual o resultado de 15 % 2 (módulo)?", options: ["7", "1", "0", "7.5"], answer: 1 },
    { question: "Em programação, o que significa 'Concatenar'?", options: ["Somar dois números", "Unir duas ou mais strings", "Dividir um valor", "Apagar um arquivo"], answer: 1 },
    { question: "Se 'P ou Q' é verdadeiro e 'P' é falso, o que podemos dizer de 'Q'?", options: ["Q é falso", "Q é verdadeiro", "Q é nulo", "Não podemos afirmar"], answer: 1 },
    { question: "Qual o operador de 'Diferente de' em Python?", options: ["<>", "===", "!=", "not="], answer: 2 },
    { question: "O que é uma 'Constante'?", options: ["Uma variável que muda sempre", "Um valor que não se altera durante a execução", "Um erro de loop", "Uma função"], answer: 1 }
];

const staticEnglishEasy = [
    { question: "O que significa o termo 'Database' em Ciência de Dados?", options: ["Base de dados", "Data de nascimento", "Computador central", "Rede de cabos"], answer: 0 },
    { question: "Qual a tradução correta para a palavra 'File'?", options: ["Fila", "Arquivo", "Fio", "Campo"], answer: 1 },
    { question: "Traduzindo para o contexto de TI, o que significa 'Search'?", options: ["Pesquisar", "Salvar", "Sair", "Subir"], answer: 0 },
    { question: "Em bancos de dados, o que é uma 'Query'?", options: ["Um erro de sistema", "Uma consulta", "Um quadro de avisos", "Uma senha"], answer: 1 },
    { question: "Na estrutura de uma tabela, o que significa 'Row'?", options: ["Linha", "Coluna", "Célula", "Título"], answer: 0 },
    { question: "Como se diz 'Desenvolvedor' em inglês?", options: ["Devedor", "Developer", "Driver", "Designer"], answer: 1 },
    { question: "O que significa 'Data Science'?", options: ["Ciência de Dados", "Ciência de Datas", "Ciência de Dança", "Ciência de Discos"], answer: 0 },
    { question: "O que é um 'Bug' no desenvolvimento de software?", options: ["Um novo recurso", "Um erro ou falha no sistema", "Um tipo de conexão", "Uma peça do hardware"], answer: 1 },
    { question: "O que significa o processo de 'Debug'?", options: ["Criar novos bugs", "Depurar ou corrigir erros", "Deletar o banco de dados", "Desligar o servidor"], answer: 1 },
    { question: "Em sistemas, o que representa o termo 'Input'?", options: ["Saída de dados", "Entrada de dados", "Processamento interno", "Impressão de arquivos"], answer: 1 },
    { question: "E o que representa o termo 'Output'?", options: ["Entrada de dados", "Saída de dados", "Memória RAM", "Disco Rígido"], answer: 1 },
    { question: "Como traduzimos 'Network' no contexto tecnológico?", options: ["Trabalho de casa", "Rede", "Notícia", "Navegador"], answer: 1 },
    { question: "O que significa o comando 'Save'?", options: ["Sair", "Salvar", "Subir", "Somar"], answer: 1 },
    { question: "O que significa 'Update'?", options: ["Atualizar", "Apagar", "Atrasar", "Anotar"], answer: 0 },
    { question: "Em um banco de dados, o que é uma 'Key' (Chave)?", options: ["Uma fechadura física", "Um identificador único", "Uma senha de usuário", "Um tipo de monitor"], answer: 1 },
    { question: "<div class='text-snippet'>'Python is a programming language that lets you work quickly and integrate systems more effectively.'</div>\nSegundo o texto, o que o Python permite?", options: ["Trabalhar devagar", "Trabalhar rápido e integrar sistemas", "Apenas somar números", "Desligar o servidor"], answer: 1 },
    { question: "<div class='text-snippet'>'A file is a collection of data stored in one unit, identified by a filename.'</div>\nO que identifica um arquivo segundo o texto?", options: ["O tamanho", "O nome do arquivo (filename)", "A cor do ícone", "A data de criação"], answer: 1 },
    { question: "<div class='text-snippet'>'Hardware represents the physical parts of a computer, such as the monitor and keyboard.'</div>\nO que é hardware?", options: ["A parte lógica", "As partes físicas do computador", "O sistema operacional", "A conexão de internet"], answer: 1 },
    { question: "Como se traduz o comando 'Print'?", options: ["Pintar", "Imprimir ou Exibir", "Pular", "Preencher"], answer: 1 },
    { question: "O que significa 'Login'?", options: ["Sair", "Entrar/Identificar-se", "Limpar", "Listar"], answer: 1 },
    { question: "Qual a tradução de 'Network'?", options: ["Trabalho", "Rede", "Notícia", "Número"], answer: 1 },
    { question: "O que é um 'Server'?", options: ["Servente", "Servidor", "Serviço", "Série"], answer: 1 }
];

const staticLogicMedium = [
    { question: "O que acontece se a condição de um 'if' for falsa e não houver um 'else'?", options: ["O programa trava", "O bloco é ignorado e o código segue", "Um erro é exibido", "O computador reinicia"], answer: 1 },
    { question: "Quando o bloco dentro de um 'else' é executado?", options: ["Sempre", "Nunca", "Quando a condição do 'if' é verdadeira", "Quando a condição do 'if' é falsa"], answer: 3 },
    { question: "Para que serve a estrutura 'elif' (ou 'else if')?", options: ["Para criar um loop", "Para testar múltiplas condições em sequência", "Para deletar variáveis", "Para imprimir dados"], answer: 1 },
    { question: "Qual o principal risco de um loop 'while' com uma condição que nunca muda para falso?", options: ["O código fica mais rápido", "O computador economiza energia", "Gera um loop infinito", "Nada acontece"], answer: 2 },
    { question: "No loop 'for', qual função é comumente usada para gerar uma sequência de números (ex: 0 a 9)?", options: ["list()", "range()", "seq()", "loop()"], answer: 1 },
    { question: "Como acessamos o primeiro elemento de uma lista chamada 'dados'?", options: ["dados[1]", "dados[0]", "dados.first()", "dados{0}"], answer: 1 },
    { question: "Qual a principal diferença entre uma Lista e uma Tupla?", options: ["A lista é azul e a tupla é verde", "A lista é mutável e a tupla é imutável", "A tupla é mais lenta", "Não há diferença"], answer: 1 },
    { question: "Em um Dicionário, os dados são armazenados em pares de...", options: ["Número e Texto", "Lista e Tupla", "Chave e Valor", "Nome e Idade"], answer: 2 },
    { question: "Qual método transforma todos os caracteres de uma String em maiúsculas?", options: ["upper()", "big()", "caps()", "maximize()"], answer: 0 },
    { question: "Como verificamos o tamanho (número de itens) de uma lista ou string?", options: ["size()", "count()", "length()", "len()"], answer: 3 },
    { question: "Qual o resultado da condição: if (10 > 5 and 2 < 1)?", options: ["Verdadeiro", "Falso", "Erro", "Indeterminado"], answer: 1 },
    { question: "Qual comando interrompe imediatamente a execução de um loop?", options: ["stop", "exit", "break", "end"], answer: 2 },
    { question: "Qual comando pula o restante do código atual e vai para a próxima iteração do loop?", options: ["next", "continue", "skip", "jump"], answer: 1 },
    { question: "Qual estrutura de dados usa chaves {} e armazena pares como {'nome': 'João'}?", options: ["Lista", "Dicionário", "Tupla", "Conjunto"], answer: 1 },
    { question: "O que acontece se tentarmos alterar um valor dentro de uma Tupla após criada?", options: ["O valor muda normalmente", "A tupla vira uma lista", "Ocorre um erro (TypeError)", "O valor é deletado"], answer: 2 },
    { question: "Interpretando: 'A é mais rápido que B' e 'B é mais rápido que C'. Quem é o mais lento?", options: ["A", "B", "C", "Nenhum"], answer: 2 },
    { question: "Lógica de Predicados: Se 'Nenhum erro é aceitável' e 'X é um erro', então X é:", options: ["Aceitável", "Não aceitável", "Opcional", "Indefinido"], answer: 1 },
    { question: "Se 'Se o código tem erro, ele não compila'. O código compilou. Logo:", options: ["O código tem erro", "O código não tem erro", "O compilador falhou", "O código é em Python"], answer: 1 },
    { question: "Se 'Maria é programadora ou analista'. Maria não é analista. Logo:", options: ["Maria é programadora", "Maria não é nada", "Maria é estagiária", "Não podemos afirmar"], answer: 0 },
    { question: "Qual o resultado de NOT (True AND False)?", options: ["True", "False", "Error", "Null"], answer: 0 },
    { question: "O que faz o método 'pop()' em uma lista?", options: ["Adiciona um item", "Remove e retorna o último item", "Limpa a lista", "Inverte a lista"], answer: 1 },
    { question: "Se 'Se chover, o chão fica molhado'. O chão não está molhado. Logo:", options: ["Choveu muito", "Não choveu", "O chão é impermeável", "Não podemos afirmar"], answer: 1 },
    { question: "Para que serve o operador 'in' (ex: if x in lista)?", options: ["Para deletar x", "Para verificar se x existe dentro da lista", "Para somar x à lista", "Para contar itens"], answer: 1 }
];

const staticEnglishMedium = [
    { question: "Como traduzimos 'Decision Structure' para o português?", options: ["Estrutura de Repetição", "Estrutura de Decisão", "Estrutura de Dados", "Estrutura de Design"], answer: 1 },
    { question: "Qual o significado da palavra 'If' no contexto de programação?", options: ["Então", "Senão", "Se", "Enquanto"], answer: 2 },
    { question: "O termo 'Else' pode ser traduzido como:", options: ["Se", "Senão", "Para cada", "Até que"], answer: 1 },
    { question: "O que significa 'Loop' em inglês?", options: ["Salto", "Laço ou Repetição", "Saída", "Entrada"], answer: 1 },
    { question: "A palavra 'While' significa:", options: ["Para", "Enquanto", "Se", "Faça"], answer: 1 },
    { question: "No contexto de listas, o que significa 'Range'?", options: ["Rank", "Intervalo ou Faixa", "Aleatório", "Regra"], answer: 1 },
    { question: "Como dizemos 'Dicionário' em inglês?", options: ["Directory", "Dictionary", "Doc", "Data"], answer: 1 },
    { question: "Em dicionários, o par de dados é chamado de 'Key' and '____'?", options: ["Lock", "Entry", "Value", "Item"], answer: 2 },
    { question: "O que significa 'Key' em um contexto de dados?", options: ["Fechadura", "Porta", "Chave", "Código"], answer: 2 },
    { question: "Como traduzimos o termo 'Immutable'?", options: ["Mutável", "Imutável", "Imaturo", "Imediato"], answer: 1 },
    { question: "O que é uma 'String' na programação?", options: ["Uma corda física", "Uma sequência de caracteres (texto)", "Um número inteiro", "Um erro de sistema"], answer: 1 },
    { question: "Qual a tradução de 'List'?", options: ["Lixo", "Linha", "Lista", "Lado"], answer: 2 },
    { question: "O termo 'Practical Project' significa:", options: ["Projeto Particular", "Projeto Prático", "Projeto Pronto", "Projeto Principal"], answer: 1 },
    { question: "O que significa o verbo 'To iterate'?", options: ["Interromper", "Iterar ou repetir", "Integrar", "Inverter"], answer: 1 },
    { question: "Como se diz 'Estruturas de Controle' em inglês?", options: ["Control Structures", "Command Structures", "Code Structures", "Call Structures"], answer: 0 },
    { question: "<div class='text-snippet'>'A variable is a container for storing data values. In Python, you don't need to declare the type.'</div>\nDe acordo com o texto, o que é uma variável?", options: ["Um tipo de loop", "Um container para armazenar valores de dados", "Uma função complexa", "Um erro de sintaxe"], answer: 1 },
    { question: "<div class='text-snippet'>'An algorithm is a set of step-by-step instructions for solving a problem or accomplishing a task.'</div>\nQual a definição de algoritmo no texto?", options: ["Um erro de sistema", "Um conjunto de instruções passo a passo", "Uma peça de hardware", "Um tipo de monitor"], answer: 1 },
    { question: "<div class='text-snippet'>'The \"if\" statement is used to execute a block of code only if a specified condition is true.'</div>\nQuando o bloco 'if' é executado?", options: ["Sempre", "Somente se a condição for verdadeira", "Somente se a condição for falsa", "Nunca"], answer: 1 }
];

const staticLogicHard = [
    { question: "Qual palavra-chave é usada para definir uma função (ex: em Python)?", options: ["func", "def", "function", "define"], answer: 1 },
    { question: "Qual a principal vantagem de usar Funções em um programa?", options: ["Deixar o código mais lento", "Reutilização de código e organização", "Esconder erros", "Aumentar o tamanho do arquivo"], answer: 1 },
    { question: "Como passamos valores externos para serem usados dentro de uma função?", options: ["Por e-mail", "Através de argumentos ou parâmetros", "Não é possível passar valores", "Usando apenas variáveis globais"], answer: 1 },
    { question: "Qual comando faz uma função enviar um resultado de volta para quem a chamou?", options: ["send", "output", "back", "return"], answer: 3 },
    { question: "O que significa 'Modularização' na programação?", options: ["Dividir o programa em partes menores e independentes", "Juntar todo o código em uma única linha", "Deletar módulos antigos", "Mudar a cor do editor"], answer: 0 },
    { question: "Para que serve o comando 'import'?", options: ["Exportar dados para PDF", "Trazer funções de outros arquivos ou bibliotecas", "Imprimir mensagens", "Salvar o projeto"], answer: 1 },
    { question: "O que é o 'Escopo' de uma variável?", options: ["O tamanho da variável", "A região do código onde a variável é reconhecida", "O tipo de dado que ela guarda", "O nome da variável"], answer: 1 },
    { question: "O que é o processamento de dados?", options: ["Transformar dados brutos em informação útil", "Apenas digitar números", "Limpar o teclado do computador", "Comprar novos discos rígidos"], answer: 0 },
    { question: "Qual a primeira etapa recomendada em uma análise simples de dados?", options: ["Publicar o relatório", "Coleta e limpeza dos dados", "Deletar os dados", "Criar um gráfico sem olhar os dados"], answer: 1 },
    { question: "Qual estrutura é ideal para armazenar uma coleção de registros (ex: vários alunos)?", options: ["Apenas uma string", "Um único número", "Uma Lista de Dicionários", "Uma variável booleana"], answer: 2 },
    { question: "O que significa 'Data Cleaning' (Limpeza de Dados)?", options: ["Lavar o computador", "Remover erros e inconsistências dos dados", "Apagar todos os dados", "Mudar o formato de texto para número"], answer: 1 },
    { question: "Qual o objetivo principal de um relatório de dados?", options: ["Confundir o leitor", "Comunicar descobertas de forma clara e objetiva", "Esconder informações importantes", "Apenas mostrar números aleatórios"], answer: 1 },
    { question: "Uma função eficiente e legível deve ser...", options: ["Muito longa e complexa", "Focada em realizar uma única tarefa clara", "Escrita em uma única linha difícil de ler", "Sem comentários"], answer: 1 },
    { question: "O que acontece se chamarmos uma função que não foi definida?", options: ["O programa ignora", "Ocorre um erro de nome (NameError)", "A função é criada automaticamente", "O computador trava"], answer: 1 },
    { question: "Em um projeto de dados, o que é fundamental?", options: ["Resolver um problema real usando lógica e dados", "Apenas copiar código da internet", "Não testar os resultados", "Usar o máximo de linhas possível"], answer: 0 },
    { question: "Silogismo: 'Alguns scripts são lentos' e 'Todo script lento deve ser otimizado'. Logo:", options: ["Todo script deve ser otimizado", "Alguns scripts devem ser otimizados", "Nenhum script é lento", "Todos os scripts são rápidos"], answer: 1 },
    { question: "Condicional: 'Se o banco de dados cair, o site fica offline'. O site está online. Logo:", options: ["O banco de dados caiu", "O banco de dados não caiu", "O site vai cair", "O banco está em manutenção"], answer: 1 },
    { question: "Se 'Todo cientista de dados sabe Python' e 'João é cientista de dados', podemos concluir:", options: ["João sabe Python", "João não sabe Python", "João está aprendendo", "Não sabemos"], answer: 0 }
];

const staticEnglishHard = [
    { question: "Como traduzimos o termo 'Accuracy' em Ciência de Dados?", options: ["Acurácia ou Precisão", "Acúmulo de dados", "Acesso rápido", "Ação imediata"], answer: 0 },
    { question: "O que é um 'Bar Chart'?", options: ["Gráfico de Pizza", "Gráfico de Barras", "Gráfico de Linha", "Tabela"], answer: 1 },
    { question: "No ambiente corporativo, o que significa 'Performance'?", options: ["Apresentação", "Desempenho", "Preferência", "Permanência"], answer: 1 },
    { question: "Como dizemos 'Relatório' em inglês?", options: ["Record", "Relation", "Report", "Review"], answer: 2 },
    { question: "O termo 'Deadline' refere-se a:", options: ["Linha de código", "Prazo final", "Data de início", "Fim da reunião"], answer: 1 },
    { question: "O que é um 'Abstract' em um artigo técnico?", options: ["Um erro", "O resumo do trabalho", "O título", "As referências"], answer: 1 },
    { question: "Como traduzimos 'Stakeholder'?", options: ["Funcionário", "Parte interessada no projeto", "Dono da empresa", "Gerente de TI"], answer: 1 },
    { question: "Em um gráfico, o que representa o 'X-axis'?", options: ["Eixo vertical", "Eixo horizontal", "Legenda", "Título"], answer: 1 },
    { question: "O que significa o termo 'Insight'?", options: ["Entrada de dados", "Percepção ou compreensão profunda", "Luz interna", "Saída de emergência"], answer: 1 },
    { question: "Como dizemos 'Previsão' em inglês (muito usado em modelos)?", options: ["Pastcast", "Forecast", "Precast", "Nowcast"], answer: 1 },
    { question: "O termo 'Throughput' refere-se a:", options: ["Capacidade total", "Vazão ou Taxa de transferência", "Entrada de luz", "Tempo de espera"], answer: 1 },
    { question: "Como se diz 'Reunião' em inglês?", options: ["Meet", "Meeting", "Union", "Session"], answer: 1 },
    { question: "O que significa 'Increase' em um gráfico de tendências?", options: ["Aumento", "Diminuição", "Estabilidade", "Erro"], answer: 0 },
    { question: "A palavra 'Feedback' é usada para:", options: ["Dar um retorno sobre o desempenho", "Apagar arquivos", "Reiniciar o sistema", "Enviar um e-mail"], answer: 0 },
    { question: "Como traduzimos 'Professional English'?", options: ["Inglês Professor", "Inglês Profissional", "Inglês Prático", "Inglês Principal"], answer: 1 },
    { question: "<div class='text-snippet'>'Cloud computing is the on-demand availability of computer system resources, especially data storage and computing power, without direct active management.'</div>\nQual a principal característica citada?", options: ["Gerenciamento ativo", "Disponibilidade sob demanda sem gerenciamento direto", "Somente para fotos", "Requer cabos"], answer: 1 },
    { question: "<div class='text-snippet'>'Data science is an interdisciplinary field that uses scientific methods, processes, and algorithms to extract knowledge from data.'</div>\nO que o campo utiliza para extrair conhecimento?", options: ["Apenas sorte", "Métodos científicos, processos e algoritmos", "Apenas planilhas", "Conversas casuais"], answer: 1 }
];

const staticLogicExtreme = [
    { question: "Qual é a complexidade de tempo do algoritmo de ordenação 'Merge Sort' no pior caso?", options: ["O(n)", "O(n^2)", "O(n log n)", "O(log n)"], answer: 2 },
    { question: "O que caracteriza uma 'Função Recursiva'?", options: ["Uma função que nunca termina", "Uma função que chama a si mesma", "Uma função sem argumentos", "Uma função que só aceita números"], answer: 1 },
    { question: "Em Python, o que faz o comando 'yield' dentro de uma função?", options: ["Encerra a função imediatamente", "Transforma a função em um gerador (iterable)", "Deleta a função da memória", "Soma dois valores"], answer: 1 },
    { question: "O que é 'Big O Notation'?", options: ["Um tipo de fonte de texto", "Uma métrica para descrever a eficiência de um algoritmo", "Um erro de sintaxe", "O nome de uma biblioteca"], answer: 1 },
    { question: "Qual a complexidade de busca em uma 'Hash Map' (caso médio)?", options: ["O(n)", "O(log n)", "O(1)", "O(n^2)"], answer: 2 },
    { question: "O que acontece se uma recursão não tiver um 'Caso Base'?", options: ["O código roda mais rápido", "Estouro de pilha (Stack Overflow)", "A recursão para sozinha", "Nada acontece"], answer: 1 },
    { question: "O que são 'Lambda Functions'?", options: ["Funções anônimas de uma única linha", "Funções que controlam o monitor", "Funções exclusivas para jogos", "Erros de compilador"], answer: 0 },
    { question: "Qual a diferença principal entre Multithreading e Multiprocessing?", options: ["Nenhuma", "Threads compartilham memória, processos não", "Processos são mais rápidos que threads", "Threads só existem em Windows"], answer: 1 },
    { question: "O que é 'Polimorfismo' na Programação Orientada a Objetos?", options: ["Mudar a cor das variáveis", "Capacidade de um objeto ser tratado como diferentes formas", "Deletar objetos antigos", "Criar múltiplas cópias do mesmo arquivo"], answer: 1 },
    { question: "Em expressões regulares (RegEx), o que o símbolo '^' representa?", options: ["Fim da string", "Início da string", "Qualquer caractere", "Um espaço em branco"], answer: 1 },
    { question: "Qual é a complexidade de um loop aninhado (um dentro do outro) percorrendo 'n' itens?", options: ["O(n)", "O(2n)", "O(n^2)", "O(log n)"], answer: 2 },
    { question: "O que faz um 'Decorator' em Python?", options: ["Muda o papel de parede", "Modifica ou estende o comportamento de uma função", "Aumenta a velocidade do processador", "Instala novos programas"], answer: 1 },
    { question: "O que é 'Memory Leak'?", options: ["Um vazamento físico de água no PC", "Falha em liberar memória que não está mais sendo usada", "Aumento da memória RAM disponível", "Um tipo de vírus"], answer: 1 },
    { question: "Qual estrutura de dados funciona no sistema LIFO (Last In, First Out)?", options: ["Fila (Queue)", "Pilha (Stack)", "Lista (List)", "Dicionário (Dict)"], answer: 1 },
    { question: "O que é um algoritmo de 'Busca Binária'?", options: ["Busca item por item", "Divide a lista ao meio repetidamente para encontrar o item", "Busca apenas números binários", "Um erro de busca"], answer: 1 },
    { question: "Paradoxo: 'Esta frase é falsa'. Se a frase for verdadeira, ela é:", options: ["Veradeira", "Falsa", "Nula", "Inexistente"], answer: 1 },
    { question: "Análise: 'Se e somente se a chave for válida, o acesso é permitido'. O acesso foi negado. Logo:", options: ["A chave é válida", "A chave é inválida", "A porta está trancada", "O sistema falhou"], answer: 1 },
    { question: "Lógica: 'Nenhum A é B. Todo C é A'. Logo:", options: ["Todo C é B", "Nenhum C é B", "Algum C é B", "Algum B é C"], answer: 1 }
];

const staticEnglishExtreme = [
    { question: "Como traduzimos 'Scalability' no contexto de sistemas?", options: ["Escalabilidade", "Escada de dados", "Equilíbrio", "Estabilidade"], answer: 0 },
    { question: "O que significa 'Asynchronous' (ou Async)?", options: ["Síncrono", "Assíncrono (não ocorre ao mesmo tempo)", "Atrasado", "Acelerado"], answer: 1 },
    { question: "O que é um 'Legacy System'?", options: ["Um sistema novo", "Um sistema legado (antigo ainda em uso)", "Um sistema legal", "Um sistema de leis"], answer: 1 },
    { question: "O termo 'Refactoring' refere-se a:", options: ["Criar novas falhas", "Reestruturar o código sem mudar seu comportamento", "Deletar o código", "Traduzir o código"], answer: 1 },
    { question: "O que é um 'Deployment Pipeline'?", options: ["Um cano de água", "Um fluxo automatizado de entrega de software", "Uma lista de funcionários", "Um erro de rede"], answer: 1 },
    { question: "Como traduzimos 'Middleware'?", options: ["Software de meio de campo", "Camada de software entre sistemas", "Hardware central", "Software final"], answer: 1 },
    { question: "O termo 'Latency' significa:", options: ["Largura de banda", "Latência ou Atraso de resposta", "Velocidade máxima", "Conexão total"], answer: 1 },
    { question: "O que significa 'Encryption'?", options: ["Descrição", "Criptografia", "Escrita", "Impressão"], answer: 1 },
    { question: "O termo 'Cloud Computing' refere-se a:", options: ["Computação em nuvem", "Computação por chuva", "Computação em rede local", "Computação sem internet"], answer: 0 },
    { question: "Como dizemos 'Ponto de extremidade' (usado em APIs)?", options: ["Finishline", "Endpoint", "Startpoint", "Baseline"], answer: 1 },
    { question: "O que significa 'Redundancy' em infraestrutura?", options: ["Falta de espaço", "Redundância (duplicação para segurança)", "Redução de custos", "Repetição de erros"], answer: 1 },
    { question: "O termo 'Framework' pode ser traduzido como:", options: ["Moldura de trabalho", "Estrutura ou arcabouço", "Fim de semana", "Ferramenta de busca"], answer: 1 },
    { question: "O que significa 'Benchmarking'?", options: ["Sentar no banco", "Avaliação comparativa de desempenho", "Marcação de código", "Fim da execução"], answer: 1 },
    { question: "Como traduzimos 'Cybersecurity'?", options: ["Ciber-segurança", "Ciber-espaço", "Ciber-ataque", "Ciber-crime"], answer: 0 },
    { question: "O termo 'API Integration' refere-se a:", options: ["Integração de API", "Integração de Pessoas", "Integração de Hardware", "Integração de Redes"], answer: 0 },
    { question: "<div class='text-snippet'>'Microservices architecture is an approach in which a large application is built as a suite of modular components or services.'</div>\nO que caracteriza essa arquitetura?", options: ["Aplicação gigante única", "Suíte de componentes ou serviços modulares", "Novo hardware", "Banco de dados central"], answer: 1 },
    { question: "<div class='text-snippet'>'Encryption is the process of encoding information. This process converts the original representation of the information into an alternative form known as ciphertext.'</div>\nO que a criptografia faz?", options: ["Deleta dados", "Converte informação para uma forma alternativa (ciphertext)", "Imprime documentos", "Aumenta a velocidade"], answer: 1 }
];

const staticInformaticsEasy = [
    { question: "Qual desses componentes é considerado o 'cérebro' do computador?", options: ["Monitor", "Teclado", "CPU (Processador)", "Impressora"], answer: 2 },
    { question: "O que significa a sigla RAM?", options: ["Read Access Memory", "Random Access Memory", "Rapid Action Module", "Real Archive Mode"], answer: 1 },
    { question: "Qual dispositivo é usado exclusivamente para entrada de dados?", options: ["Monitor", "Impressora", "Teclado", "Caixa de som"], answer: 2 },
    { question: "O Windows, o Linux e o macOS são exemplos de:", options: ["Navegadores", "Sistemas Operacionais", "Editores de Texto", "Hardwares"], answer: 1 },
    { question: "Qual o principal objetivo de um antivírus?", options: ["Aumentar a velocidade da internet", "Proteger o PC contra softwares maliciosos", "Limpar a poeira do monitor", "Melhorar a qualidade das fotos"], answer: 1 },
    { question: "O que é um 'Browser'?", options: ["Um tipo de vírus", "Um navegador de internet", "Uma peça do hardware", "Um editor de planilhas"], answer: 1 },
    { question: "Qual o atalho padrão para 'Copiar' um item no Windows?", options: ["Ctrl + V", "Ctrl + X", "Ctrl + C", "Ctrl + Z"], answer: 2 },
    { question: "Onde os arquivos costumam ser armazenados permanentemente?", options: ["Memória RAM", "Processador", "Disco Rígido (HD/SSD)", "Placa de Vídeo"], answer: 2 },
    { question: "Qual empresa criou o sistema operacional Windows?", options: ["Apple", "Google", "Microsoft", "Samsung"], answer: 2 },
    { question: "O que é o 'Google Chrome'?", options: ["Um sistema operacional", "Um navegador", "Um hardware", "Um antivírus"], answer: 1 },
    { question: "Para que serve a tecla 'Enter'?", options: ["Apagar texto", "Confirmar uma ação ou quebrar linha", "Cancelar um comando", "Mudar a cor da letra"], answer: 1 },
    { question: "O que significa 'Download'?", options: ["Enviar um arquivo para a internet", "Baixar um arquivo da internet para o PC", "Excluir um arquivo", "Renomear uma pasta"], answer: 1 },
    { question: "O que é um 'Hardware'?", options: ["A parte lógica (programas)", "A parte física do computador", "Um tipo de vírus", "Uma senha"], answer: 1 },
    { question: "Qual dessas opções é um periférico de saída?", options: ["Microfone", "Mouse", "Impressora", "Scanner"], answer: 2 },
    { question: "O que é o 'Desktop'?", options: ["A parte de trás do computador", "A área de trabalho do sistema operacional", "Um tipo de cabo", "O botão de desligar"], answer: 1 },
    { question: "O que significa a sigla USB?", options: ["Universal Serial Bus", "United Service Box", "User Speed Board", "Ultra Small Battery"], answer: 0 },
    { question: "Qual dessas é uma unidade de medida de armazenamento?", options: ["Hertz", "Gigabyte (GB)", "Volt", "Ampere"], answer: 1 },
    { question: "O que é o 'Wi-Fi'?", options: ["Um cabo de energia", "Tecnologia de rede sem fio", "Um tipo de monitor", "Um antivírus"], answer: 1 },
    { question: "Para que serve o 'Caps Lock'?", options: ["Apagar letras", "Escrever tudo em maiúsculo", "Mudar o brilho", "Desligar o PC"], answer: 1 }
];

const staticInformaticsMedium = [
    { question: "Qual a função da tecla 'F5' na maioria dos navegadores?", options: ["Fechar a aba", "Atualizar a página", "Abrir o histórico", "Imprimir a tela"], answer: 1 },
    { question: "O que é o 'Painel de Controle' no Windows?", options: ["Um jogo", "Local para gerenciar configurações do sistema", "Uma peça física", "Onde se limpa o teclado"], answer: 1 },
    { question: "Qual o significado de 'HTTP'?", options: ["Hypertext Transfer Protocol", "High Tech Transfer Process", "Home Text Tool Pro", "Hyper Tool Transfer Path"], answer: 0 },
    { question: "Qual dessas extensões é comumente usada para arquivos de imagem?", options: [".docx", ".exe", ".jpg", ".mp3"], answer: 2 },
    { question: "O que é o 'Cesto de Lixo' (Lixeira) nos computadores?", options: ["Onde ficam os vírus", "Local de armazenamento temporário de arquivos deletados", "Onde se limpa a memória RAM", "Um hardware de descarte"], answer: 1 },
    { question: "O que significa a sigla URL?", options: ["User Remote Link", "Uniform Resource Locator", "Universal Radio Line", "United Resource List"], answer: 1 },
    { question: "Qual a função principal do Microsoft Excel?", options: ["Editar vídeos", "Criar planilhas e cálculos", "Navegar na internet", "Enviar e-mails"], answer: 1 },
    { question: "O que é 'Nuvem' (Cloud Storage)?", options: ["Armazenamento local no HD", "Armazenamento de dados em servidores remotos via internet", "Um tipo de clima", "Um hardware que flutua"], answer: 1 },
    { question: "Qual o atalho para 'Colar' um item?", options: ["Ctrl + C", "Ctrl + V", "Ctrl + P", "Ctrl + S"], answer: 1 },
    { question: "O que é o 'Kernel' de um sistema operacional?", options: ["A interface visual", "O núcleo que gerencia recursos entre hardware e software", "O antivírus", "O teclado virtual"], answer: 1 },
    { question: "Qual a diferença entre HTTP e HTTPS?", options: ["O HTTPS é mais lento", "O HTTPS possui uma camada de segurança/criptografia", "Não há diferença", "O HTTP é apenas para celulares"], answer: 1 },
    { question: "O que é um 'Driver'?", options: ["Um motorista de Uber", "Um software que permite a comunicação entre o SO e o hardware", "Uma peça de metal", "Um tipo de pasta"], answer: 1 },
    { question: "Qual o atalho para alternar entre janelas abertas no Windows?", options: ["Alt + Tab", "Ctrl + Esc", "Shift + Enter", "Alt + F4"], answer: 0 },
    { question: "O que é o 'Firewall'?", options: ["Uma parede de fogo física", "Um sistema de segurança que controla o tráfego de rede", "Um programa para queimar CDs", "O ventilador do processador"], answer: 1 },
    { question: "O que significa a sigla PDF?", options: ["Personal Data File", "Portable Document Format", "Printable Digital Form", "Public Data Folder"], answer: 1 }
];

const staticInformaticsHard = [
    { question: "Qual o valor decimal do número binário 1010?", options: ["8", "10", "12", "15"], answer: 1 },
    { question: "O que é o 'BIOS' de um computador?", options: ["Um sistema operacional moderno", "Firmware que inicializa o hardware durante o boot", "Um tipo de vírus potente", "O manual do usuário"], answer: 1 },
    { question: "Qual a principal função do protocolo SMTP?", options: ["Receber e-mails", "Enviar e-mails", "Navegar na web", "Transferir arquivos grandes"], answer: 1 },
    { question: "O que é 'Overclocking'?", options: ["Desligar o PC rapidamente", "Aumentar a frequência do processador além do padrão", "Limpar a memória cache", "Instalar dois sistemas operacionais"], answer: 1 },
    { question: "Qual a principal diferença entre SSD e HDD?", options: ["O HDD é mais rápido", "O SSD não possui partes móveis e é muito mais rápido", "O SSD é mais barato", "Não há diferença de velocidade"], answer: 1 },
    { question: "O que é um 'IP Estático'?", options: ["Um endereço IP que muda sempre", "Um endereço IP fixo atribuído a um dispositivo", "Um vírus de rede", "A velocidade da internet"], answer: 1 },
    { question: "O que significa a sigla SQL?", options: ["Simple Quest Language", "Structured Query Language", "System Quality List", "Sequential Query Log"], answer: 1 },
    { question: "Qual a função do comando 'PING'?", options: ["Aumentar a velocidade", "Testar a conectividade entre dois dispositivos na rede", "Deletar arquivos", "Reiniciar o roteador"], answer: 1 },
    { question: "O que é 'Phishing'?", options: ["Um esporte de pesca", "Uma técnica de fraude para obter dados confidenciais", "Um tipo de processador", "Um novo navegador"], answer: 1 },
    { question: "O que é o 'Cache' do processador?", options: ["Um tipo de dinheiro digital", "Memória de acesso ultrarrápido próxima ao núcleo", "O cooler do PC", "Onde ficam as fotos"], answer: 1 },
    { question: "Qual camada do modelo OSI é responsável pelo roteamento (IP)?", options: ["Camada Física", "Camada de Rede", "Camada de Transporte", "Camada de Aplicação"], answer: 1 },
    { question: "O que é 'Dual Boot'?", options: ["Ter dois monitores", "Ter dois sistemas operacionais instalados no mesmo PC", "Ligar o PC duas vezes", "Ter duas memórias RAM"], answer: 1 },
    { question: "O que significa a sigla RAID em armazenamento?", options: ["Rapid Access Internal Disk", "Redundant Array of Independent Disks", "Real Archive Interactive Data", "Remote Access Interface Device"], answer: 1 },
    { question: "Qual a função principal do protocolo DHCP?", options: ["Criptografar dados", "Atribuir endereços IP automaticamente na rede", "Enviar e-mails", "Controlar a velocidade do cooler"], answer: 1 },
    { question: "O que é 'Open Source' (Código Aberto)?", options: ["Software que deve ser pago", "Software cujo código-fonte é público e pode ser modificado", "Software que não tem ícone", "Software exclusivo da Microsoft"], answer: 1 }
];

const staticInformaticsExtreme = [
    { question: "Qual o endereço IP de 'Loopback' padrão (Localhost)?", options: ["192.168.0.1", "127.0.0.1", "10.0.0.1", "8.8.8.8"], answer: 1 },
    { question: "Em um sistema de 64 bits, qual a quantidade máxima teórica de RAM endereçável?", options: ["4 GB", "16 GB", "16 Exabytes", "1 Terabyte"], answer: 2 },
    { question: "O que é um 'Kernel Panic'?", options: ["Um jogo de terror", "Um erro crítico de sistema no Unix/Linux", "O ventilador parando", "Uma senha errada"], answer: 1 },
    { question: "O que faz o comando 'tracert' (ou traceroute)?", options: ["Apaga o histórico", "Mostra o caminho percorrido pelos pacotes até um destino", "Aumenta o sinal do Wi-Fi", "Muda o IP"], answer: 1 },
    { question: "Qual a função do registro 'MX' em uma zona de DNS?", options: ["Mapear um domínio para um IP", "Identificar servidores de e-mail do domínio", "Criar um apelido para o site", "Aumentar a segurança"], answer: 1 },
    { question: "O que é 'Latência' em redes de computadores?", options: ["A largura de banda", "O tempo de atraso entre o envio e o recebimento de dados", "O número de usuários", "A força do sinal"], answer: 1 },
    { question: "Qual o sistema de arquivos padrão usado pelo Windows (versões modernas)?", options: ["FAT32", "NTFS", "EXT4", "APFS"], answer: 1 },
    { question: "O que é 'Virtualização'?", options: ["Criar um PC de brinquedo", "Executar múltiplos sistemas operacionais isolados em um único hardware", "Usar óculos VR", "Navegar na internet"], answer: 1 },
    { question: "O que é um 'Zero-Day Vulnerability'?", options: ["Uma falha descoberta no dia zero", "Uma falha de segurança desconhecida pelos desenvolvedores", "Um vírus que dura um dia", "Uma senha que expira rápido"], answer: 1 },
    { question: "Qual protocolo é usado para acesso remoto seguro via terminal?", options: ["Telnet", "SSH", "FTP", "HTTP"], answer: 1 },
    { question: "O que significa 'Endianness' em arquitetura de computadores?", options: ["O fim da execução", "A ordem em que os bytes são armazenados na memória", "O tamanho do processador", "A cor da placa mãe"], answer: 1 },
    { question: "O que é o 'Active Directory' (AD)?", options: ["Uma pasta de fotos", "Serviço de diretório da Microsoft para gerenciamento de rede", "Um tipo de monitor", "Um antivírus da Apple"], answer: 1 },
    { question: "O que faz uma 'VPN'?", options: ["Aumenta a velocidade do PC", "Cria um túnel criptografado para tráfego de dados na rede", "Limpa arquivos temporários", "Troca a placa de vídeo"], answer: 1 },
    { question: "Qual a principal diferença entre TCP e UDP?", options: ["O UDP é mais lento", "O TCP é orientado à conexão e garante a entrega, o UDP não", "O TCP é apenas para vídeos", "Não há diferença"], answer: 1 },
    { question: "O que é o 'Registry' (Registro) do Windows?", options: ["Uma lista de compras", "Banco de dados central de configurações do sistema e aplicativos", "Onde se registra o nome do usuário", "Um backup na nuvem"], answer: 1 }
];


const staticDataScienceEasy = [
    { question: "Qual a diferença entre 'Dado' e 'Informação'?", options: ["São a mesma coisa", "Dados são fatos brutos; Informação é o dado processado e com contexto", "Informação é o que guardamos no HD", "Dados são apenas números"], answer: 1 },
    { question: "O que caracteriza um dado 'Booleano'?", options: ["Números decimais", "Textos longos", "Valores verdadeiro ou falso", "Datas e horários"], answer: 2 },
    { question: "Qual dessas opções é um exemplo de 'Dado Não Estruturado'?", options: ["Uma tabela SQL", "Uma planilha Excel", "Um vídeo ou arquivo de áudio", "Um arquivo CSV"], answer: 2 },
    { question: "O que significa a sigla SGBD?", options: ["Sistema de Gestão de Banco de Dados", "Software Gráfico de Banco de Dados", "Servidor Geral de Busca de Dados", "Sequência Geral de Blocos de Dados"], answer: 0 },
    { question: "Na modelagem de dados, o que representa o 'MER'?", options: ["Modelo de Execução Rápida", "Modelo Entidade-Relacionamento", "Módulo de Entrada e Retorno", "Mapeamento de Erros e Registros"], answer: 1 },
    { question: "Qual comando SQL é usado para extrair dados de uma tabela?", options: ["INSERT", "CREATE", "SELECT", "UPDATE"], answer: 2 },
    { question: "Para que serve a cláusula 'WHERE' no SQL?", options: ["Para criar uma tabela", "Para filtrar registros específicos", "Para deletar o banco de dados", "Para ordenar os resultados"], answer: 1 },
    { question: "O que é uma 'Entidade' em um banco de dados?", options: ["Um comando SQL", "Um objeto do mundo real (como Aluno ou Produto)", "Uma senha de acesso", "Um erro de sistema"], answer: 1 },
    { question: "Qual comando é usado para inserir novos registros em uma tabela?", options: ["SELECT", "ADD", "INSERT", "CREATE"], answer: 2 },
    { question: "Qual tipo de dado é mais adequado para armazenar o preço de um produto?", options: ["Texto", "Booleano", "Numérico/Decimal", "Data"], answer: 2 },
    { question: "O que é a 'Modelagem Conceitual'?", options: ["A criação do código SQL", "A definição das tabelas no HD", "A representação abstrata e de alto nível dos dados", "A instalação do SGBD"], answer: 2 },
    { question: "Em SQL, o comando 'CREATE TABLE' serve para:", options: ["Inserir dados", "Apagar dados", "Criar uma nova tabela", "Mudar o nome de uma coluna"], answer: 2 },
    { question: "Qual a função do 'Conhecimento' no ciclo de dados?", options: ["Apenas guardar arquivos", "A aplicação prática da informação para tomada de decisão", "Criar tabelas", "Digitar textos"], answer: 1 },
    { question: "Um arquivo de texto simples (.txt) é geralmente considerado:", options: ["Dado Estruturado", "Dado Semi-estruturado ou Não Estruturado", "Banco de Dados Relacional", "Metadata"], answer: 1 },
    { question: "O que é um 'Atributo' no MER?", options: ["Uma conexão entre tabelas", "Uma característica ou propriedade de uma entidade", "Um tipo de servidor", "Um comando de exclusão"], answer: 1 }
];

const staticDataScienceMedium = [
    { question: "Qual comando SQL é utilizado para modificar registros existentes?", options: ["CHANGE", "MODIFY", "UPDATE", "SET"], answer: 2 },
    { question: "O que acontece se você executar um 'DELETE' sem a cláusula 'WHERE'?", options: ["Nada acontece", "Apenas o primeiro registro é apagado", "Todos os registros da tabela são apagados", "O SQL retorna um erro"], answer: 2 },
    { question: "Para que serve uma 'Primary Key' (Chave Primária)?", options: ["Para criptografar os dados", "Para identificar unicamente cada registro em uma tabela", "Para permitir valores duplicados", "Para ligar o computador"], answer: 1 },
    { question: "O que é uma 'Foreign Key' (Chave Estrangeira)?", options: ["Uma chave de outro país", "Uma chave que identifica registros em outra tabela para criar relacionamentos", "Uma senha mestra", "Uma chave que não pode ser usada"], answer: 1 },
    { question: "Qual a função da constraint 'NOT NULL'?", options: ["Permite valores vazios", "Impede que uma coluna aceite valores nulos", "Apaga dados nulos", "Esconde a coluna"], answer: 1 },
    { question: "O que faz o comando 'INNER JOIN'?", options: ["Retorna apenas registros que possuem correspondência em ambas as tabelas", "Retorna todos os registros de uma tabela só", "Cria uma nova tabela", "Deleta dados duplicados"], answer: 0 },
    { question: "Para que servem as 'Funções de Agregação' (como SUM, AVG, COUNT)?", options: ["Para apagar dados", "Para realizar cálculos em um conjunto de valores e retornar um único valor", "Para criar novos usuários", "Para formatar textos"], answer: 1 },
    { question: "A cláusula 'GROUP BY' é usada para:", options: ["Deletar grupos de dados", "Agrupar linhas que têm os mesmos valores em colunas específicas", "Mudar o nome do banco", "Ordenar alfabeticamente"], answer: 1 },
    { question: "Qual a diferença entre 'HAVING' e 'WHERE'?", options: ["Não há diferença", "WHERE filtra linhas; HAVING filtra grupos após o GROUP BY", "HAVING é mais rápido", "WHERE só funciona com números"], answer: 1 },
    { question: "O que é uma 'Subconsulta' (Subquery)?", options: ["Uma consulta dentro de outra consulta", "Uma consulta pequena", "Um erro de SQL", "Uma consulta que não retorna nada"], answer: 0 },
    { question: "Para que serve uma 'View' no banco de dados?", options: ["Para ver fotos", "Para criar uma tabela virtual baseada no resultado de uma consulta SELECT", "Para aumentar a velocidade do HD", "Para deletar logs"], answer: 1 },
    { question: "O que é um 'Índice' (Index) no SQL?", options: ["Uma lista de tabelas", "Uma estrutura que melhora a velocidade de busca de dados", "O número da página", "Um comando de inserção"], answer: 1 },
    { question: "Qual relacionamento é representado quando um Aluno pode ter vários Livros, mas cada Livro pertence a apenas um Aluno?", options: ["1:1 (Um para um)", "1:N (Um para muitos)", "N:N (Muitos para muitos)", "N:1 (Muitos para um)"], answer: 1 },
    { question: "A constraint 'UNIQUE' garante que:", options: ["Todos os valores sejam nulos", "Todos os valores em uma coluna sejam diferentes", "A tabela tenha apenas um registro", "O banco seja seguro"], answer: 1 },
    { question: "Qual função de agregação retorna o valor mais alto de uma coluna?", options: ["MIN()", "SUM()", "MAX()", "TOP()"], answer: 2 }
];

const staticDataScienceHard = [
    { question: "No contexto de engenharia de dados, o que significa 'ETL'?", options: ["Electronic Table Logic", "Extract, Transform, Load", "Execute, Transfer, List", "Edit, Type, Link"], answer: 1 },
    { question: "Qual a principal diferença entre sistemas OLTP e OLAP?", options: ["OLTP é para análise; OLAP é para transações", "OLTP foca em transações rápidas; OLAP foca em consultas analíticas complexas", "OLTP é mais caro", "OLAP não usa SQL"], answer: 1 },
    { question: "O que é um 'Data Warehouse'?", options: ["Uma sala cheia de servidores", "Um sistema de armazenamento otimizado para análise de grandes volumes de dados", "Um tipo de pendrive", "Um site de downloads"], answer: 1 },
    { question: "O que é o processo de 'Data Cleaning' (Limpeza de Dados)?", options: ["Passar um pano no servidor", "Identificar e corrigir dados corrompidos, incorretos ou irrelevantes", "Apagar todo o banco de dados", "Mudar o formato de data"], answer: 1 },
    { question: "No modelo dimensional, o que é uma 'Tabela Fato'?", options: ["Uma tabela com descrições de texto", "Uma tabela que contém métricas quantitativas e chaves para dimensões", "Uma tabela que armazena nomes de pessoas", "Uma tabela temporária"], answer: 1 },
    { question: "O que são 'Dimensões' em um ambiente analítico?", options: ["O tamanho do arquivo", "Atributos descritivos que contextualizam os fatos (Ex: Tempo, Local, Produto)", "O número de colunas", "O tempo de resposta do servidor"], answer: 1 },
    { question: "O que caracteriza a 'Padronização' de dados?", options: ["Deixar todos os dados em maiúsculo", "Colocar os dados em um formato uniforme (Ex: Datas como AAAA-MM-DD)", "Excluir dados antigos", "Usar apenas números"], answer: 1 },
    { question: "Qual técnica é usada para transformar dados de linhas em colunas no SQL?", options: ["JOIN", "UNION", "PIVOT", "GROUP BY"], answer: 2 },
    { question: "O que é 'Performance Tuning' em SQL?", options: ["Mudar a cor do editor", "Ajustar consultas e o banco para que rodem de forma mais rápida e eficiente", "Aumentar a memória RAM", "Comprar um novo servidor"], answer: 1 },
    { question: "Qual a vantagem de usar 'Joins Avançados' (como LEFT/RIGHT OUTER JOIN)?", options: ["São mais simples", "Permitem trazer dados mesmo quando não há correspondência exata em uma das tabelas", "Não precisam de chaves", "Rodam sempre mais rápido"], answer: 1 },
    { question: "O que é o esquema 'Star Schema'?", options: ["Um desenho de estrela", "Um modelo dimensional com uma tabela fato central ligada a várias dimensões", "Um tipo de rede", "Um protocolo de segurança"], answer: 1 },
    { question: "O que significa 'Normalização' de banco de dados?", options: ["Deixar o banco com nome normal", "Organizar os dados para reduzir redundância e proteger a integridade", "Aumentar o número de tabelas infinitamente", "Usar apenas chaves primárias"], answer: 1 },
    { question: "Uma 'Consulta Analítica' geralmente envolve:", options: ["Apenas um SELECT simples", "Agregações complexas sobre grandes volumes de dados históricos", "Inserção de um único registro", "Criação de novos usuários"], answer: 1 },
    { question: "O que é 'Latência de Dados'?", options: ["O peso do arquivo", "O tempo decorrido entre a geração do dado e sua disponibilidade para uso", "O número de erros", "A cor dos dados"], answer: 1 },
    { question: "Qual o benefício de usar 'Índices' em colunas usadas frequentemente no WHERE?", options: ["Diminui o tamanho do banco", "Aumenta drasticamente a velocidade de recuperação dos dados", "Bloqueia acessos não autorizados", "Apaga dados duplicados"], answer: 1 }
];

const staticDataScienceExtreme = [
    { question: "O que diferencia um 'Data Lake' de um 'Data Warehouse'?", options: ["O preço", "Data Lake armazena dados brutos (raw); Data Warehouse armazena dados estruturados e tratados", "Data Lake é apenas para fotos", "Não há diferença técnica"], answer: 1 },
    { question: "Qual o impacto de 'Excesso de Índices' em uma tabela com muitos INSERTs/UPDATEs?", options: ["Nenhum impacto", "Melhora a performance de escrita", "Degrada a performance de escrita, pois cada índice deve ser atualizado", "Aumenta a segurança"], answer: 2 },
    { question: "O que é 'SCD' (Slowly Changing Dimensions)?", options: ["Dimensões que nunca mudam", "Técnicas para gerenciar mudanças nos dados das dimensões ao longo do tempo", "Um erro de disco rígido", "Um tipo de JOIN"], answer: 1 },
    { question: "Qual a função do 'Optimizer' (Otimizador) no SGBD?", options: ["Limpar o cache", "Escolher o caminho mais eficiente para executar uma consulta SQL", "Aumentar a velocidade da CPU", "Mudar as senhas"], answer: 1 },
    { question: "O que é 'Data Lineage' (Linhagem de Dados)?", options: ["A árvore genealógica do DBA", "O rastreamento do ciclo de vida do dado, desde a origem até o destino", "O tamanho total do banco", "A cor dos gráficos"], answer: 1 },
    { question: "Em ambientes Big Data, o que é 'V de Variedade'?", options: ["Muitos servidores", "Diferentes tipos e fontes de dados (Estruturados, Semi e Não Estruturados)", "Velocidade de acesso", "Volume de dados"], answer: 1 },
    { question: "O que define uma 'Transação ACID'?", options: ["Acidez dos dados", "Propriedades de Atomicidade, Consistência, Isolamento e Durabilidade", "Um tipo de backup", "Uma consulta rápida"], answer: 1 },
    { question: "O que é 'Normalização até a 3ª Forma Normal (3NF)'?", options: ["Ter 3 tabelas", "Eliminar dependências transitivas para garantir integridade", "Mudar o nome das colunas 3 vezes", "Usar 3 chaves primárias"], answer: 1 },
    { question: "Qual o risco de 'Denormalização' em um Data Warehouse?", options: ["Melhorar a performance", "Aumentar a redundância e o risco de inconsistência, mas facilitar a consulta analítica", "Nenhum risco", "O banco parar de funcionar"], answer: 1 },
    { question: "O que é um 'Full Outer Join'?", options: ["Um JOIN que não funciona", "Retorna todos os registros de ambas as tabelas, unindo onde há correspondência e trazendo NULL onde não há", "Um JOIN apenas para chaves", "Um comando de deleção"], answer: 1 },
    { question: "O que caracteriza o processamento 'In-Memory Computing'?", options: ["Usar menos RAM", "Processar dados diretamente na memória RAM para ultra-velocidade", "Guardar dados no processador", "Usar apenas o HD"], answer: 1 },
    { question: "O que é 'Data Governance' (Governança de Dados)?", options: ["O dono da empresa", "Políticas e padrões para garantir a qualidade, segurança e usabilidade dos dados", "O departamento de TI", "Um software antivírus"], answer: 1 },
    { question: "Qual o objetivo de 'Métricas de Qualidade de Dados' (Data Quality)?", options: ["Ter muitos dados", "Medir precisão, completude, consistência e validade dos dados", "Aumentar o número de colunas", "Diminuir o custo de storage"], answer: 1 },
    { question: "O que é 'Materialized View' (View Materializada)?", options: ["Uma view comum", "Uma view cujo resultado é armazenado fisicamente em disco para performance", "Uma view que só mostra imagens", "Um backup da view"], answer: 1 },
    { question: "O que é 'Sharding' em bancos de dados distribuídos?", options: ["Excluir dados", "Dividir horizontalmente os dados de uma tabela em vários servidores", "Aumentar o tamanho da coluna", "Criptografar o banco"], answer: 1 }
];
